export const BUSINESS_TYPES = [
  {
    id: 'grocery',
    label: 'Grocery / Kirana',
    emoji: '\u{1F6D2}',
    defaultCategories: ['Grains', 'Pulses', 'Oils', 'Dairy', 'Snacks', 'Essentials', 'Beverages', 'Spices'],
    placeholder: 'e.g. Basmati Rice (5kg)',
    categoryHint: 'e.g. Grains',
    voiceExamples: [
      '"10 bags of Basmati Rice at 120 rupees each"',
      '"5 litres Saffola Gold oil, 850 rupees"',
      '"Amul Butter 500g, dairy, 280 rupees"',
    ],
    voiceHint: '"20 packets of Maggi at 14 rupees, snacks"',
  },
  {
    id: 'music_instruments',
    label: 'Music Instruments',
    emoji: '\u{1F3B8}',
    defaultCategories: ['Guitars', 'Keyboards', 'Drums', 'Strings', 'Accessories', 'Amplifiers'],
    placeholder: 'e.g. Yamaha F310 Guitar',
    categoryHint: 'e.g. Guitars',
    voiceExamples: [
      '"2 Yamaha F310 acoustic guitars at 7500 each"',
      '"Casio CTX-700 keyboard, 1 piece, 12000 rupees"',
      '"10 sets of guitar strings, accessories, 150 rupees each"',
    ],
    voiceHint: '"1 Roland drum pad, drums, 25000 rupees"',
  },
  {
    id: 'bikes',
    label: 'Bikes & Automobiles',
    emoji: '\u{1F3CD}\uFE0F',
    defaultCategories: ['Bikes', 'Parts', 'Accessories', 'Lubricants', 'Tyres', 'Helmets'],
    placeholder: 'e.g. Royal Enfield Classic 350',
    categoryHint: 'e.g. Bikes',
    voiceExamples: [
      '"1 Royal Enfield Classic 350, bikes, 195000 rupees"',
      '"4 Castrol engine oil 1 litre, lubricants, 350 each"',
      '"10 MRF tyres size 90/90, tyres, 1200 rupees each"',
    ],
    voiceHint: '"2 Studds helmets, accessories, 800 rupees each"',
  },
  {
    id: 'gold_jewelry',
    label: 'Gold & Jewelry',
    emoji: '\u{1F48E}',
    defaultCategories: ['Gold', 'Silver', 'Diamonds', 'Gemstones', 'Chains', 'Rings', 'Bangles'],
    placeholder: 'e.g. Gold Chain 22K (10g)',
    categoryHint: 'e.g. Gold',
    voiceExamples: [
      '"1 gold chain 22 karat 10 grams, 62000 rupees"',
      '"5 silver bangles, silver, 1500 rupees each"',
      '"2 diamond earrings, diamonds, 35000 rupees each"',
    ],
    voiceHint: '"1 gold ring 18 karat, rings, 28000 rupees"',
  },
  {
    id: 'electronics',
    label: 'Electronics',
    emoji: '\u{1F4F1}',
    defaultCategories: ['Mobiles', 'Laptops', 'Accessories', 'Cables', 'Audio', 'Storage'],
    placeholder: 'e.g. Samsung Galaxy S24',
    categoryHint: 'e.g. Mobiles',
    voiceExamples: [
      '"3 Samsung Galaxy Buds, audio, 4500 rupees each"',
      '"1 MacBook Air M3, laptops, 114900 rupees"',
      '"20 USB-C cables, cables, 150 rupees each"',
    ],
    voiceHint: '"5 iPhone 15 cases, accessories, 500 rupees each"',
  },
  {
    id: 'clothing',
    label: 'Clothing & Textiles',
    emoji: '\u{1F455}',
    defaultCategories: ['Men', 'Women', 'Kids', 'Ethnic', 'Casual', 'Formal'],
    placeholder: 'e.g. Levi\'s Slim Fit Jeans',
    categoryHint: 'e.g. Men',
    voiceExamples: [
      '"10 cotton shirts size L, men, 450 rupees each"',
      '"5 sarees silk, women ethnic, 2500 rupees each"',
      '"20 kids t-shirts, kids casual, 250 rupees each"',
    ],
    voiceHint: '"15 formal trousers, men formal, 900 rupees each"',
  },
  {
    id: 'pharmacy',
    label: 'Pharmacy / Medical',
    emoji: '\u{1F48A}',
    defaultCategories: ['Medicines', 'Supplements', 'First Aid', 'Personal Care', 'Baby Care'],
    placeholder: 'e.g. Dolo 650 (strip of 15)',
    categoryHint: 'e.g. Medicines',
    voiceExamples: [
      '"50 strips Dolo 650, medicines, 30 rupees each"',
      '"10 bottles Crocin syrup, medicines, 85 rupees each"',
      '"20 band-aid packs, first aid, 45 rupees each"',
    ],
    voiceHint: '"30 Centrum multivitamins, supplements, 650 rupees each"',
  },
  {
    id: 'hardware',
    label: 'Hardware & Tools',
    emoji: '\u{1F527}',
    defaultCategories: ['Power Tools', 'Hand Tools', 'Plumbing', 'Electrical', 'Paint', 'Fasteners'],
    placeholder: 'e.g. Bosch Drill Machine',
    categoryHint: 'e.g. Power Tools',
    voiceExamples: [
      '"3 Bosch drill machines, power tools, 3500 each"',
      '"50 kg nails 2 inch, fasteners, 80 rupees per kg"',
      '"10 litres Asian Paints white, paint, 450 each"',
    ],
    voiceHint: '"5 Stanley hammers, hand tools, 350 rupees each"',
  },
  {
    id: 'stationery',
    label: 'Stationery & Books',
    emoji: '\u{1F4DA}',
    defaultCategories: ['Notebooks', 'Pens', 'Books', 'Art Supplies', 'Office', 'Bags'],
    placeholder: 'e.g. Classmate Notebook (200 pages)',
    categoryHint: 'e.g. Notebooks',
    voiceExamples: [
      '"100 Classmate notebooks 200 pages, 45 rupees each"',
      '"50 Reynolds pens blue, pens, 10 rupees each"',
      '"20 Apsara pencil boxes, art supplies, 60 each"',
    ],
    voiceHint: '"30 Cello gel pens, pens, 25 rupees each"',
  },
  {
    id: 'general',
    label: 'General Store',
    emoji: '\u{1F3EA}',
    defaultCategories: ['Food', 'Household', 'Personal Care', 'Cleaning', 'Misc'],
    placeholder: 'e.g. Surf Excel 1kg',
    categoryHint: 'e.g. Household',
    voiceExamples: [
      '"10 Surf Excel 1 kg packs, cleaning, 250 each"',
      '"20 Dove soap bars, personal care, 55 rupees each"',
      '"5 Broom sticks, household, 80 rupees each"',
    ],
    voiceHint: '"15 Colgate toothpaste, personal care, 95 rupees each"',
  },
];

export const DEFAULT_CATEGORIES = ['General', 'Food', 'Household', 'Personal', 'Electronics', 'Other'];
